#Module 1

###Strings

In [ ]:
#Split Text
text = "Hello my name is da vinci"
splitted_text = text.split(' ')
print(splitted_text)

#Join Splitted text back with single blank space
joined_text = ' '.join(splitted_text)
print(joined_text)

#strip spaces
word = '  Hello   '
striped_word = word.strip()
print(striped_word)

#Replace old word with new word
new_text = text.replace('da vinci', 'john cena')
print(new_text)

#Upper and Lower Case
print(text.upper())
print(text.lower())

#RegEx

['Hello', 'my', 'name', 'is', 'da', 'vinci']
Hello my name is da vinci
Hello
Hello my name is john cena
HELLO MY NAME IS DA VINCI
hello my name is da vinci


###Lists

In [ ]:
#comprehension
lst = [x for x in range(1,5)]
print(lst)

#lets sort it in descending order
sorted_list = sorted(lst, reverse=True)
print(sorted_list)

#slicing
print(lst[1:3])

#removing duplicates
lst.append(2)
print(lst)
print(list(set(lst)))

[1, 2, 3, 4]
[4, 3, 2, 1]
[2, 3]
[1, 2, 3, 4, 2]
[1, 2, 3, 4]


### Dictioanries

In [ ]:
#counting using collections.counter, defaultdict,

#iterating
d={'a':123,'b':456}
for k,v in d.items():
  print(k,v)

a 123
b 456


### Sets

In [ ]:
set1 = set([1,2,3,4])
set2 = set([2,3,5,6])

#union
print(set1.union(set2))

#intersection
print(set1.intersection(set2))

#difference
print(set1.difference(set2))

{1, 2, 3, 4, 5, 6}
{2, 3}
{1, 4}


### Problems

In [ ]:
#Problem 1: Email domain counter
text= '''alice@gmail.com
bob@yahoo.com
carol@gmail.com
dave@outlook.com
eve@yahoo.com'''

emailMap = {}
for email in text.split('\n'):
  k = email.split('@')[1]
  if k in emailMap:
    emailMap[k] += 1
  else:
    emailMap[k] = 1

for k,v in emailMap.items():
  print(k,v)

gmail.com 2
yahoo.com 2
outlook.com 1


In [ ]:
#Problem 2: Top 3 words
text = 'This is a test. This test is only a test.'
text = text.replace('.','')
wordMap =  {}
for word in text.split(' '):
  if word in wordMap:
    wordMap[word]+=1
  else:
    wordMap[word]=1

for word, count in sorted(wordMap.items(), key = lambda x:x[1], reverse=True)[:3]:
  print(word, count)

test 3
This 2
is 2


In [ ]:
#Problem 3: Sort By Age ascending, then score descending in Name, Age, Score data
studentsData = [
    ['Alice', 30, 90],
    ['Bob', 25, 85],
    ['Carol', 25, 92],
    ['Dave', 30, 85]
]


[['Alice', 30, 90], ['Bob', 25, 85], ['Carol', 25, 92], ['Dave', 30, 85]]

In [ ]:
sorted(studentsData, key=lambda x: (x[1], -x[2]))

[['Carol', 25, 92], ['Bob', 25, 85], ['Alice', 30, 90], ['Dave', 30, 85]]

# Module 2

### Numpy

In [ ]:
import numpy as np

#Numpy Array
arr = np.array([1,2,3,4,5])
print(arr)

#Range of values between stop, start , jump
range_arr = np.arange(1,10,2)
print(range_arr)

#Equally divide values between start, stop, paritions
print(np.linspace(1,10,20))

#Zeros matrix
np.zeros((4,5))

#Ones matrix
np.ones((3,2))

[1 2 3 4 5]
[1 3 5 7 9]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Array Math

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr+5)
print(arr-3)
print(arr*3)
print(arr/4)
print(arr%2)

#Indexing and Slicing
print(arr[1:4])

[ 6  7  8  9 10]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[0.25 0.5  0.75 1.   1.25]
[1 0 1 0 1]
[2 3 4]


### Masking

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr < 3 #Boolean value
arr[mask]

array([1, 2])

### Aggregations

In [ ]:
# Mean
print(np.mean(arr))

# Std
print(np.std(arr))

# Min, Max
print(np.min(arr))

# Position with max value
print(np.argmax(arr))

3.0
1.4142135623730951
1
4


### Problems

In [ ]:
#Problem 1: Extract Even Numbers
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr%2==0])

[2 4]


In [ ]:
#Problem 2: Highest Score Per Student
scores = np.array([
    [85, 90, 78],
    [88, 76, 95],
    [92, 89, 96]
])

np.max(scores, axis=1)

array([90, 95, 96])

In [ ]:
#Problem 3: normalize it (subtract mean, divide by std).
arr = np.array([10, 20, 30, 40, 50])
arr = arr - np.mean(arr)
arr/np.std(arr)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

# Module 3

### DataFrame

In [ ]:
# Read from csv file
# df = pd.read_csv('data.csv')

#create a DataFrame from a dictionary
students = {
    "Alice": {"age": 30, "score": 90},
    "Bob": {"age": 25, "score": 85},
    "Carol": {"age": 25, "score": 92},
    "Dave": {"age": 30, "score": 85}
}

import pandas as pd
df = pd.DataFrame(students)
print(df.head())

#Data Selection
print(df['Alice'])

#Multiple column selection
print(df[['Alice', 'Bob']])

#Loc
print(df.loc['age','Alice'])

#iloc
print(df.iloc[0,2:4])

#Masking
df[df['Alice']<25]

       Alice  Bob  Carol  Dave
age       30   25     25    30
score     90   85     92    85
age      30
score    90
Name: Alice, dtype: int64
       Alice  Bob
age       30   25
score     90   85
30
Carol    25
Dave     30
Name: age, dtype: int64


Empty DataFrame
Columns: [Alice, Bob, Carol, Dave]
Index: []

### Cleaning Data

In [ ]:
# Drop null values
df.dropna()

#FIll na with some value
df.fillna(10)

#Rename columns
df.rename(columns = {'Alice': 'Col1', 'Bob': 'Col2', 'Carol': 'Col3', 'Dave':'Col4'}, inplace=True)

#Replace values
df.replace({'Col1':{30:40}}, inplace=True)

#Change Data Type
df['Col1'] = df['Col1'].astype(float)

Col1  Col2  Col3  Col4
age    40.0    25    25    30
score  90.0    85    92    85

### Aggregation

In [ ]:
#Group BY
df.groupby('Col1')['Col2'].sum()

#Aggregate multiple columns
df.groupby('Col1').agg({'Col2': 'sum', 'Col3': 'mean'})

Col2  Col3
Col1            
40.0    25  25.0
90.0    85  92.0

### Sorting

In [ ]:
#sort by Col1 ascending, and then Col2 descneding
df.sort_values(by=['Col1', 'Col2'], ascending=[True, False])

Col1  Col2  Col3  Col4
age    40.0    25    25    30
score  90.0    85    92    85

### Merge

In [ ]:
df1 = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Carol', 'Dave'],
    'age': [20, 21, 22, 23]
})

df2 = pd.DataFrame({
    'student_id': [1, 2, 4, 5],
    'score': [88, 92, 79, 85]
})

pd.merge(df1, df2, on="student_id", how="inner")

student_id   name  age  score
0           1  Alice   20     88
1           2    Bob   21     92
2           4   Dave   23     79

### Problems

In [ ]:
#Problem1: Find total sales by region
data = {
    'Region': ['East', 'West', 'East', 'North', 'West'],
    'Sales': [200, 300, 150, 400, 250]
}

df = pd.DataFrame(data)
df.groupby('Region')['Sales'].sum()

Region
East     350
North    400
West     550
Name: Sales, dtype: int64

In [ ]:
#Problem 2: Top Earners Per Department
data = [
    {'Name': 'Alice', 'Department': 'IT', 'Salary': 90000},
    {'Name': 'Bob', 'Department': 'HR', 'Salary': 60000},
    {'Name': 'Carol', 'Department': 'IT', 'Salary': 95000},
    {'Name': 'Dave', 'Department': 'Finance', 'Salary': 70000},
    {'Name': 'Eve', 'Department': 'Finance', 'Salary': 85000}
]

df = pd.DataFrame(data)
#here transform acts as a window function, and adds max value in each record of that grouped column i.e Department, and further can be used as a mask
#to select the one that matches with it.
mask = df.groupby('Department')['Salary'].transform('max')
df[df['Salary']== mask]

Name Department  Salary
1    Bob         HR   60000
2  Carol         IT   95000
4    Eve    Finance   85000

In [ ]:
#Problem 3: Filter by Year 2024
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'Dave'],
    'JoinDate': ['2023-05-01', '2024-01-15', '2024-07-20', '2022-11-11']
}

df = pd.DataFrame(data)
df[df['JoinDate'].str.startswith('2024')]

Name    JoinDate
1    Bob  2024-01-15
2  Carol  2024-07-20

In [ ]:
###DateTime
#if there is a column in date format, always first convert it into dateTime format as
import pandas as pd
df = pd.DataFrame({
    "date": ["2025-09-04 15:30:45", "2025-01-01 08:15:00"]
})

df['newCol'] = pd.to_datetime(df['date'])
print(df['newCol'].dt.strftime('%Y-%m-%d'))
print(df['newCol'].dt.day)

0    2025-09-04
1    2025-01-01
Name: newCol, dtype: object
0    4
1    1
Name: newCol, dtype: int32


# Module 4

### File Reading

In [ ]:
#Read all data at once
with open('dummy.txt', 'rb') as f:
  content = f.read()
  print(content)

#Read line by line
with open('dummy.txt', 'rb') as f:
  for line in f:
    print(line,end='')

#Writing into the file
with open('dummy.txt', 'a') as f:
  f.write('Apple eats ball')

b'Apple eats ballApple eats ballApple eats ballApple eats ball'
b'Apple eats ballApple eats ballApple eats ballApple eats ball'

### JSON

In [ ]:
import json
json_str = '''
{
  "name": "Alice",
  "age": 25,
  "skills": ["Python", "SQL", "AWS"],
  "address": {
    "city": "Mumbai",
    "pincode": 400001
  }
}
'''

#convert json to python dictionary(to read json, we convert it to dictionary using json.loads)
data_dct = json.loads(json_str)

print(data_dct)

#convert it back to json string
jstr = json.dumps(data_dct)

print(jstr)

{'name': 'Alice', 'age': 25, 'skills': ['Python', 'SQL', 'AWS'], 'address': {'city': 'Mumbai', 'pincode': 400001}}
{"name": "Alice", "age": 25, "skills": ["Python", "SQL", "AWS"], "address": {"city": "Mumbai", "pincode": 400001}}
